language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - kuofp@cs.nctu.edu.tw
    on_success: always
    on_failure: always

script: phpunit